Draft: Feature 1054/link requestee to process
oci-labs/check-ins pull request #1079
Opened 2021-06-25 18:48 UTC by JEdwardBrown

Link works the way it is supposed to, but I keep getting an internal server error

2021-06-28 14:34 UTC, moshirim approved these changes

2021-06-30 15:40 UTC, pieperm requested changes
Navigating to `/feedback/request` via the URL automatically puts the user on the recipient selection step

2021-06-30 15:40 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +  //const numbersOnly = /^\d+$/.test(stepQuery);
This commented line can be deleted, since we no longer use regex to validate the `stepQuery`

2021-06-30 15:40 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +      // );
We want this `<Redirect>` uncommented for now (there's another PR that will replace it eventually)

2021-06-30 15:40 UTC, pieperm commented on web-ui/src/components/personnel/Personnel.jsx
> +const createFeedbackRequestLink = (memberId) => (<Link className="feedback-link" to={`/feedback/request?for=${memberId}&step=1`}>Request Feedback</Link>);
Slight change: link to `/feedback/request/?for=etc` (adding a slash in front of the question mark) This does not change anything functionality-wise but keeps it consistent with our other URLs

2021-06-30 15:40 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +  const id = values.for;
I would recommend getting the `for` search parameter similar to how we do it for the other parameters:
```
const for = query.for?.toString();
```

2021-07-02 17:06 UTC, pieperm requested changes
This renders feedback templates outside of `FeedbackTemplateSelector`. We need to make sure that PRs start to use `FeedbackTemplateSelector` so we can a lot of template-specific logic out of `FeedbackRequestPage`

2021-07-02 19:12 UTC, pieperm approved these changes

2021-07-05 18:02 UTC, Maroju100 approved these changes

2021-07-06 13:49 UTC, merged