Feature 1084/search templates
oci-labs/check-ins pull request #1095
Opened 2021-06-29 17:30 UTC by sagetheherb

This pr lets the user search templates and provides a message if there are no matching templates

2021-06-30 15:16 UTC, pieperm requested changes
The page currently breaks if you go to step 3

2021-06-30 15:16 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +      }
This logic can be simplified a bit

2021-06-30 15:16 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +                    ? <h2>No matching templates</h2>
This renders even if there are no templates to display, regardless of whether the user has entered any search text. Maybe something like:
```
{searchText === "" && filteredTemplates.length === 0 &&
<h2>No templates found</h2>}
{searchText && searchText.length > 0 && filteredTemplates.length === 0 &&
<h2>No matching templates</h2>}

2021-06-30 17:27 UTC, sagetheherb commented
> The page currently breaks if you go to step 3

I am not sure whats breaking this, looking into it but if anyone else has an idea let me know.

2021-07-08 18:09 UTC, JEdwardBrown approved these changes

2021-07-08 18:22 UTC, HootDunk approved these changes
Looks good!  I'd just add the missing key prop and then merge.

2021-07-08 18:22 UTC, HootDunk commented on web-ui/src/components/feedback_template_selector/FeedbackTemplateSelector.jsx
> +                  <TemplateCard
I noticed React was giving warnings about a missing key prop here so you may want to re-add that but otherwise it looks good!

2021-07-08 18:22 UTC, HootDunk commented on web-ui/src/components/feedback_template_selector/FeedbackTemplateSelector.jsx
> +          (filteredTemplates.length === 0 && searchText === "")
JS has truthy and falsy values.  Zeros and empty strings are both falsy meaning they will evaluate to false by default so you can just write it as (!filteredTemplates.length && !searchText).  I wouldn't worry about changing it here but figured I'd mention it as it's a nice time saver.
https://www.sitepoint.com/javascript-truthy-falsy/

2021-07-08 18:22 UTC, HootDunk commented on web-ui/src/components/feedback_template_selector/FeedbackTemplateSelector.jsx
> +              : (searchText && searchText.length >= 0 && filteredTemplates.length === 0)
This can also use the Truthy/Falsy evaluation to write it like so -> (searchText && !filteredTemplates.length)

2021-07-08 19:04 UTC, merged