Feature 1098/validation for feedback request date selection
oci-labs/check-ins pull request #1136
Opened 2021-07-06 21:05 UTC by JEdwardBrown

2021-07-08 17:02 UTC, moshirim approved these changes

2021-07-09 14:47 UTC, bhatiam12 commented
@smithj11 @JEdwardBrown 
builds are failing -
```./src/pages/FeedbackRequestPage.jsx
  Line 139:8:  React Hook useCallback has a missing dependency: 'handleSubmit'. Either include it or remove the dependency array  react-hooks/exhaustive-deps```

2021-07-09 14:50 UTC, JEdwardBrown commented
Yep! Just some issues that are popping after fixing some merge conflicts, I'm working on them now.

2021-07-09 16:30 UTC, JEdwardBrown commented
@bhatiam12 everything should be working fine now

2021-07-09 16:56 UTC, sagetheherb approved these changes

2021-07-09 16:59 UTC, bhatiam12 approved these changes

2021-07-09 19:00 UTC, pieperm requested changes

2021-07-09 19:00 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +      if(dueQuery && dueQuery !== undefined) {
This can be simplified to `if (dueQuery) {`

2021-07-09 19:00 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +
I don't think this block does anything?

2021-07-09 19:00 UTC, pieperm commented on web-ui/src/pages/FeedbackRequestPage.jsx
> +      return (sendQuery && isValidDate(sendQuery) && isValidPair)
Would it make more sense to move the logic for `isValidPair` into the `isValidDate` function?

2021-07-09 20:35 UTC, pieperm approved these changes

2021-07-09 20:36 UTC, merged