Bugfix 1418/misc bugfixes
oci-labs/check-ins pull request #1420
Opened 2021-08-11 21:24 UTC by smithj11

Does the following:
--Fixes ad hoc public/private creation issue 
--Fixes suggestion ID being current user instead of requestee
--Shortens autosave debounce time

2021-08-16 14:07 UTC, mkimberlin requested changes

2021-08-24 20:26 UTC, jahanner commented on server/src/main/java/com/objectcomputing/checkins/notifications/email/MailJetSender.java
> +        LOG.debug("address " + FROM_NAME);
do we need to keep these?

2021-08-24 20:26 UTC, jahanner commented on server/src/main/java/com/objectcomputing/checkins/services/feedback_request/FeedbackRequestServicesImpl.java
> +//        String newContent =  notificationContent + "<a href=\""+submitURL+storedRequest.getId()+"\">Check-Ins application</a>.";
should we remove this?

2021-08-24 20:27 UTC, jahanner commented on web-ui/src/components/feedback_recipient_selector/FeedbackRecipientSelector.jsx
> +      console.log(" get suggestions res " + JSON.stringify(res))
probably should remove this

2021-08-24 20:27 UTC, jahanner approved these changes

2021-08-25 15:06 UTC, mkimberlin approved these changes

2021-08-25 15:07 UTC, merged