Feature 390/dev setup documentation
oci-labs/check-ins pull request #396
Opened 2020-10-12 19:57 UTC by warnerj-oci

Notes in Contributing doc for technology installs for dev environment.

2020-10-13 14:30 UTC, Bagurp approved these changes

2020-10-22 14:12 UTC, Maroju100 approved these changes

2020-10-22 14:15 UTC, Maroju100 commented on CONTRIBUTING.md
> +- Gradle 6.3
Not sure, dev setup documents looks fine for now. We can update it latter if we still have the issue.

2020-10-22 19:38 UTC, meyerinj requested changes
It looks like something went wrong it Git here. I suggest making a new branch off of dev and putting only the expected changes on it, then we'll close down this PR.

2020-10-22 20:16 UTC, meyerinj commented
Replaced with #423 as this merge appears to have been polluted with other changes and I don't know how to pick them apart.

2020-10-22 20:16 UTC, closed without merging