Created service for tagging entities
oci-labs/check-ins pull request #740
Opened 2021-03-03 19:31 UTC by moshirim

2021-03-05 19:13 UTC, sonndinh reviewed
Overall the code looks good to me; most of my comments are minor. Another structural thing is that there are 2 new services added to the same subdirectory `checkins/services/tags`, but seems to me we should have one subdirectory for each new service, based on how other services are organized.

2021-03-05 19:13 UTC, sonndinh commented on LICENSE
> +      "Licensor" shall mean the copyright owner or Tag authorized by
Looks like "entity"s are replaced by "Tag"s by mistake in this file?

2021-03-08 15:29 UTC, mkimberlin requested changes
See comments. I also unresolved a number of @sonndinh 's comments as they have not been addressed in the code yet and are valid.

2021-03-08 15:29 UTC, mkimberlin commented on LICENSE
> +      "Licensor" shall mean the copyright owner or Tag authorized by
All of the changes in this file need to be reverted. It's the License for the project.

2021-03-08 15:29 UTC, mkimberlin commented on server/src/main/java/com/objectcomputing/checkins/services/tags/EntityTagServicesImpl.java
> +        permissionsValidation.validatePermissions(!isAdmin, "User is unauthorized to do this operation");
Yes, We do. Please add this @moshirim

2021-03-08 15:29 UTC, mkimberlin commented on server/src/main/java/com/objectcomputing/checkins/services/tags/TagServicesImpl.java
> +            permissionsValidation.validatePermissions(!isAdmin, "User is unauthorized to do this operation");
+1 on this as well, @moshirim

2021-03-08 15:29 UTC, mkimberlin commented on server/src/main/resources/db/common/V41__create_tags_table.sql
> +drop table if exists tags;
you are missing a drop if exists on `entity_tags`

2021-03-08 19:21 UTC, moshirim commented
All of issues mentioned 

> Overall the code looks good to me; most of my comments are minor. Another structural thing is that there are 2 new services added to the same subdirectory `checkins/services/tags`, but seems to me we should have one subdirectory for each new service, based on how other services are organized.

Thank you for your feedback Son, I took care of all of the things you mentioned. Let me know what you think.

2021-03-08 19:23 UTC, moshirim commented
> See comments. I also unresolved a number of @sonndinh 's comments as they have not been addressed in the code yet and are valid.

Should be all good now.

2021-03-09 15:43 UTC, mkimberlin commented on server/src/main/resources/db/common/V41__create_tags_table.sql
> +drop table if exists tags;
You are still missing a drop if exists on `entity_tags`.

2021-03-09 17:12 UTC, mkimberlin commented on server/src/main/resources/db/common/V41__create_tags_table.sql
> +drop table if exist entity_tags;
`exists` not `exist`

2021-03-09 19:25 UTC, sonndinh approved these changes

2021-03-09 23:12 UTC, merged