Feature 853/create team skills report closes #853
oci-labs/check-ins pull request #971
Opened 2021-06-08 17:45 UTC by jahanner

2021-06-08 18:12 UTC, mkimberlin requested changes

2021-06-08 18:12 UTC, mkimberlin commented on web-ui/src/pages/TeamSkillReportPage.css
> +.active {
You need to do some prefixing on these names. These are too generic and will eventually have clash if they don't already. Either restrict them to only applying to things that are inside this component (set a class at the top level element and include it in your match patterns in this file) or make them very unlikely to clash (prefix the classnames themselves).

2021-06-08 18:12 UTC, mkimberlin commented on web-ui/src/pages/TeamSkillReportPage.jsx
> +  function skillsToSkillLevel(skills) {
You could turn this into a selector...not a must, just a thought.

2021-06-08 18:12 UTC, mkimberlin commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Why does this file exist at the top level? Did you accidentally yarn install there? This should go away.

2021-06-10 15:59 UTC, zsbrown97 approved these changes

2021-06-10 16:44 UTC, warnerj-oci commented on web-ui/src/pages/TeamSkillReportPage.jsx
> +      setAllSearchResults([]);
Is there a reason you setAllSearchResults twice here?

2021-06-10 16:48 UTC, warnerj-oci approved these changes

2021-06-14 14:12 UTC, mkimberlin approved these changes

2021-06-14 14:12 UTC, merged